#!/bin/bash
set -e
set -xv

: ${PPA:=ppa:disqus/nginx}

on_exit() {
    git checkout master || :
}

trap 'on_exit' EXIT
on_exit

debian_prefix="ubuntu"

full_tags=($(git rev-parse --symbolic-full-name --tags))

tags=()
upstream_tags=()
debian_tags=()
ppa_tags=()
unknown_tags=()

for full_tag in "${full_tags[@]}"; do
    tag="${full_tag#refs/tags/}"

    tags+=("$tag")

    case "$tag" in
        $debian_prefix/v*)
            debian_tags+=("$tag")

            case "$tag" in
                $debian_prefix/v*ppa*)
                    ppa_tags+=("$tag")
                    ;;
            esac

            ;;
        v*)
            upstream_tags+=("$tag")
            ;;
        *)
            unknown_tags+=("$tag")
            ;;
    esac
done

echo "Tags: (${#tags[@]})"
echo "- Upstream:" "${upstream_tags[@]}"
echo "- Debian:" "${debian_tags[@]}"
echo "- PPA:" "${ppa_tags[@]}"
echo "- Unknown:" "${unknown_tags[@]}"
echo

has-tag() {
    local needle="$1"

    local tag
    for tag in "${tags[@]}"; do
        if [[ "$tag" == "$needle" ]]; then
            return 0
        fi
    done

    return 1
}

next-rev() {
    local prefix="$1"

    local rev
    for rev in {0..999}; do
        if ! has-tag "$prefix$rev"; then
            echo "$rev"
            return 0
        fi
    done

    return 1
}

taggify() {
    local tag="$debian_prefix/v${1#$debian_prefix/v}"
    tag="${tag//\~/_}"
    echo "$tag"
}

pkg=$(dpkg-parsechangelog -S Source)
base_version=$(dpkg-parsechangelog -S Version)

#git tag -f "$debian_prefix/v${base_version}"

if [[ ${#dists[@]} -eq 0 ]]; then
    dists=(zesty yakkety xenial precise trusty)
fi


do_dist() {
    local dist="$1"
    local branch="$debian_prefix/$dist"

    local pre_version="${base_version}~${dist}"
    local pre_tag_version=$(taggify "$pre_version")

    local next_rev=$(next-rev "$pre_tag_version")
    local cur_rev=$(( $next_rev - 1 ))
    [[ $cur_rev -gt 0 ]] || local cur_rev=0

    if [[ -n "$INCR" ]]; then
        local rev="$next_rev"
    else
        local rev="$cur_rev"
    fi

    local version="$pre_version$rev"
    local tag_version="$pre_tag_version$rev"

    echo
    echo "Dist: $dist branch=$branch version=$version"
    echo "---"

    echo "-- Checking out $branch"
    git checkout -B "$branch" "master"

    echo "-- Checking out $branch"
    git checkout "$branch"
    echo "-- Merging from master"
    git rebase --strategy into master

    echo "-- Updating changelog. version=$version"
    dch -b \
        --force-distribution \
        -D "$dist" \
        -v "$version" \
        "Rebuild for ${dist}"
    dch -a "Changed build-dependencies to packages available in ${dist}"

    echo "-- Committing"
    git commit -m 'Bump' debian/changelog

    echo "-- Building"
    gbp buildpackage \
      --git-debian-branch="$branch" \
      --git-submodules \
      --git-builder='debuild --preserve-envvar=CCACHE_DIR --prepend-path=/usr/lib/ccache -i -I' \
      -S -sa

    dput "$PPA" "../build-area/${pkg}_${version}_source.changes" || return 1

    echo "-- Tagging"
    git tag -f "${tag_version}"
}


for dist in "${dists[@]}"; do
    do_dist "$dist"
done

echo "DONE"

